import type { Config } from "tailwindcss";

const config: Config = {
  // We use safelist to guarantee these dynamic classes are generated by Tailwind.
  safelist: [
    'prose-lg',
    'prose-xl',
    'prose-2xl',
  ],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  // THE FIX: This plugin is REQUIRED for any 'prose-*' classes to have styling.
  // This is the most likely reason the font sizing was not working.
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
export default config;